== Introduction
:version:

http://vertx.io/[Eclipse Vert.x] is a toolkit to build reactive and distributed systems on the top of the JVM.
Vert.x applications can be developed in multiple languages such as Java, JavaScript, Groovy, Scala, Kotlin, Ceylon, Ruby...
As a toolkit, Vert.x is un-opinionated.

The maven-vertx-plugin is a plugin for Apache Maven for packaging and running Vert.x applications.
The plugin tries to provide an opinionated way to build Vert.x application:

* applications are packaged as a _fat_ jar (containing your code and all the dependencies including Vert.x)
* the application is configured with an `application.json` file or an `application.yml` file (translated to json).

The last version of the Vert.x Maven Plugin is **{version}**.

=== Using the plugin

The plugin provides a set of goals such as:

* setup - add the Vert.x Maven Plugin to your `pom.xml`
* initialize - manage _js_ dependencies and _webjars_, also initiates the redeployment
* package - package your Vert.x application as a _fat_ jar
* run - run your application
* start / stop - start your application in background / stop it

Generally, you will use the following configuration:

[source,xml,subs=attributes+]
----
<project>
  ...
  <build>
    <plugins>
        ...
        <plugin>
            <groupId>io.reactiverse</groupId>
            <artifactId>vertx-maven-plugin</artifactId>
            <version>{version}</version>
            <executions>
                <execution>
                    <id>vmp</id>
                    <goals>
                        <goal>initialize</goal>
                        <goal>package</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
  </build>
  ...
</project>
----

=== Packaging

This plugin packaged the Vert.x application as a fat or über jar.
These jars are executable, and so can be launched using: `java -jar <my-app.jar>`.
The packaging process adds certain *MANIFEST.MF* entries that control how the application is launched.
The plugin takes care of adding the required entries to the *MANIFEST.MF* with values configured using the **<<common:configurations,Common Configuration>>**

The following are the Manifest entries that will be added based on the configuration elements:

.Package configuration
[cols="1,1,5"]
|===
| Property| Manifest Attribute | Remarks

| vertx.verticle
| Main-Verticle
| The main verticle, _i.e._ the entry point of your application. Used when the `Main-Class` is `io.vertx.core.Launcher`.

| vertx.launcher
| Main-Class
| The main class used to start the application, defaults to `io.vertx.core.Launcher`
|===

The package is generated using:  `mvn clean package`

For more information on packaging refer to **<<vertx:package,vertx:package>>**

=== Running

The plugin allows running vert.x applications in following ways:

==== In foreground using **<<vertx:run,vertx:run>>**

:description:

The Vert.x application could also be run without building the fat jars, typically during the development mode.
The **<<vertx:run,vertx:run>>** goal helps in running the application.
The application will be run in as forked process with additional configurations based on the goals.

To run the application vert.x application in foreground, execute the following maven command

`mvn clean compile vertx:run`

You can enable the redeployment mode rebuilding and restarting the application upon file changes.

For more information on configuration options refer to  **<<vertx:run,vertx:run>>**

==== In background using **<<vertx:start,vertx:start>>**

:description:

This allows the application be run using the uber or fat jar as background process.
This option also attaches a configurable id or an autogenerated id which could be used to stop the process using **<<vertx:stop,vertx:stop>>**

To start the application vert.x application in background, execute the following maven command

`mvn clean install vertx:start`

For more information on configuration options refer to **<<vertx:start,vertx:start>>**

To stop the application vert.x application running in background, execute the following maven command

`mvn vertx:stop`

For more information on configuration options refer to **<<vertx:stop,vertx:stop>>**
