
= Introduction

This is a Maven plugin for packaging and running http://vertx.io/[vert.x] applications. The plugin tries to add some
intelligence to build in adding some common options automatically based on conventions, for an example
if you add file called __application.json or application.yml or application.yml__ in your src/main/conf folder of the maven sources, the file gets automatically
added as vertx *-conf* option during **<<vertx:package>>** or **<<vertx:start>>** goals.

== Packaging

The vert.x application needs to be packaged as fat or uber jar, which can then be executed
using `java -jar <my-app-fat.jar>`.  The packaging also need to add certain *MANIFEST.MF* entires
that controls the vert.x application launching.  The plugin takes care of adding the required entries
to the *MANIFEST.MF* with values configured using the **<<common:configurations,Common Configuration>>**

The following are the Manifest entries that will be added based on the configuration elements:

.Package configuration
[cols="1,1,5"]
|===
| Property| Manifest Attribute | Remarks

| vertx.verticle
| Main-Verticle
|
| vertx.launcher
| Main-class
| If custom launcher is used the Main-Class is always defaulted to `io.vertx.core.Launcher`
|===

To package the project as vert.x application, execute the following maven command

`mvn clean package vertx:package`

For more information on packaging refer to **<<vertx:package,vertx:package>>**

== Running

The plugin allows running vert.x applications in following ways:

=== In foreground using **<<vertx:run,vertx:run>>**

:description:

The vert.x application could also be run without building building the fat jars, typically during the
development mode.  The **<<vertx:run,vertx:run>>** goal helps in running the application. The
application will be run in as forked process with additional configurations based on the goals.

To run the application vert.x application in foreground, execute the following maven command

`mvn clean install vertx:run`

For more information on configuration options refer to  **<<vertx:run,vertx:run>>**

=== As a daemon using **<<vertx:start,vertx:start>>**

:description:

This allows the application be run using the uber or fat jar as background process.
This option also attaches a configurable id or an autogenerated id which could be used to stop the process
using **<<vertx:stop,vertx:stop>>**

To start the application vert.x application in background, execute the following maven command

`mvn clean install vertx:start`

For more information on configuration options refer to **<<vertx:start,vertx:start>>**

To stop the application vert.x application running in background, execute the following maven command

`mvn vertx:stop`

For more information on configuration options refer to **<<vertx:stop,vertx:stop>>**
