= Miscellaneous

== How does redeployment work?

During the _initialize_ phase, the plugin starts observing the mojos (Maven plugins) that are executed.

The Vert.x Maven Plugin watches for changes in `src/main`.
When a file or directory is changed (created, updated or deleted):

- it stops the Vert.x application
- it replays the executed mojos (all the mojos from the _generate-sources_ to the _process-classes_ phases, using the same configuration as the initial (observed) one)
- it stars the Vert.x application again

Such a mechanism lets you use any Maven plugin (executed in the right set of phases).
The plugin is re-executed and then the Vert.x application is restarted.

== Windows: command line is too long

The Vert.x Maven Plugin runs your Vert.x application in a forked process.
This process command line can grow quickly depending on:

. the number of dependencies in the project,
. the length of the path to JVM,
. the length of the path to the Maven repository.

On Windows, there is a maximum length for command lines.
When this maximum is reached the Vert.x application fails to start.
You will see an error such as:

----
Command line is too long
----

As a workaround, you can either:

* move the JVM and Maven repository paths closer to the root of the Windows drive, or
* use `subst` to associate the JVM and Maven repository paths with a drive letter.

For example, you could associate the letter `X` with the JVM path and `Y` with the Maven repository path:

[source,shell script]
----
subst X: "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot"
subst Y: "C:\Users\User\.m2\repository"
----

TIP: Virtual drives created with `subst` do not survive reboots.
To make the setup somewhat persistent, put the `subst` commands in a batch file and add it to the https://support.microsoft.com/en-us/help/4558286/windows-10-add-an-app-to-run-automatically-at-startup[startup folder].

Then:

. set the `JAVA_HOME` environment variable to `X:`
. open the Maven settings file and change the `localRepository` element value to `Y:`

NOTE: Don't forget to open a new terminal so that the environment variable change is visible.

[#_how_does_the_plugin_detect_if_a_custom_main_class_is_a_launcher]
== How does the plugin detect if a custom main class is a launcher?

Some goals must detect whether a custom main class set with the `launcher` element (see <<common:configurations>>) is a Vert.x launcher.

The Vert.x Maven plugin considers a class is a Vert.x launcher if:

* the project depends on Vert.x 4 and the class extends `io.vertx.core.Launcher`, or
* the project depends on Vert.x 5 application and:
** the class extends `io.vertx.launcher.application.VertxApplication`, or
** the class extends `io.vertx.core.Launcher`.

In the last case, of course, the project must depend on `io.vertx:vertx-launcher-legacy-cli`.

