[[vertx:setup]]
=== *vertx:setup*

This goal adds the Vert.x Maven Plugin to your `pom.xml` file.
The plugin is configured with a default configuration.

==== Example

[source,subs="attributes"]
----
mvn io.reactiverse:vertx-maven-plugin:{version}:setup
----

The setup goal by default uses the plugin property _vertx-core-version_ from the plugin properties file `vertx-maven-plugin.properties` as the Vert.x version of the project.
If you wish to override the Vert.x version, then you can run the same command as above with `-DvertxVersion=<your-vertx-version>`:

[source,subs=attributes+]
----
mvn io.reactiverse:vertx-maven-plugin:{version}:setup -DvertxVersion={vertx-core-version}
----

This will configure the vert.x and its dependencies to `{vertx-core-version}` i.e. Maven project property `vertx.version` set to `{vertx-core-version}`.

You can also generate a project if you don't have a `pom.xml` file:

[source,subs="attributes"]
----
mvn io.reactiverse:vertx-maven-plugin:{version}:setup \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=acme-project \
    -DprojectVersion=1.0-SNAPSHOT \ # default to 1.0-SNAPSHOT
    -Dverticle=org.acme.Foo
----

The `verticle` parameter creates a new verticle class file.

When creating a project, the `java.specification.version` system property is used to configure the Maven compiler plugin in the new POM file.
To set a different Java version, use the `javaVersion` property:

[source,subs=attributes+]
----
mvn io.reactiverse:vertx-maven-plugin:{version}:setup -DjavaVersion=11
----
